#!/bin/sh

function get_pipeline() {
   
   WGS_PRISM_BIN=$(pwd)
   cd "$WGS_PRISM_BIN" || exit 1
   echo "CWD: $WGS_PRISM_BIN"
   echo "Running wgs qc pipeline (press Enter to continue)"
   read answer
   exec ./_run_wgs_qc

}

get_pipeline 
