### ###
# These will be overridden by parameters passed on the CLI via the --config flag
# It is recommended that these variables are mapped in the params: and not accessed directly through the config[] dictionary
### ###

### HPC data organsiation global variables; passed via --config in practise ###
# RUN must be passed via --config parameter at runtime
# eg. 231019_A01439_0219_AHNKGFDRX3
# AKA. $RUN
RUN: "231005_A01439_0216_AHL7NKDRX3"
# eg. /dataset/2023_illumina_sequencing_[a-z]/active/$RUN
# AKA. $SEQ_ROOT
IN_ROOT: "/projects/2024_illumina_sequencing_g/run_data"
# eg. /datasets/2023_illumina_sequencing_[a-z]/scratch/postprocessing/illumina/novaseq/$RUN
# AKA. $OUTPUT_ROOT
# OUTPUT_ROOT must be passed via --config parameter at runtime
OUT_ROOT: "/projects/2024_illumina_sequencing_g/postprocessing/illumina"

### Reference Data Locations ###
human_genome_index: "/projects/2023_sequence_production/wgs_prism/resources/GRCh38/GRCh38"
kraken2_index: "/datasets/2024-kraken2-indices/k2_nt_20231129"

### multiQC configuration ###
multiqc_config: "resources/multiQC_config.yaml"


